# Spring Boot Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include: "health,info,prometheus"
    info:
      git:
        mode: full
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
      cache:
        time-to-live: 300s
    prometheus:
      enabled: true
      cache:
        time-to-live: 30s

# Swagger endpoint
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger

spring:
  jackson:
    default-property-inclusion: NON_NULL

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    allow-circular-references: true

  cloud:
    gateway:
      httpclient:
        connect-timeout: 600000
        response-timeout: 6000s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept, Content-Length, TOKEN, Authorization, sm_universalid"
            allowedMethods: "GET, POST, PATCH, PUT, DELETE, OPTIONS"
            maxAge: 3628800
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: wincar-sav
          predicates:
            - Path=/sav-api/**
          filters:
            - StripPrefix=1
          uri: lb://wincar-sav-service
        - id: wincar-auth
          predicates:
            - Path=/auth-api/**
          filters:
            - StripPrefix=1
          uri: lb://wincar-auth-service
        - id: wincar-transverse
          predicates:
            - Path=/transverse-api/**
          filters:
            - StripPrefix=1
          uri: lb://wincar-transverse-service

# profil DEV
---
spring:
  config:
    activate:
      on-profile: dev

admin-registry:
  user: dev
  password: dev

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://${admin-registry.user}:${admin-registry.password}@localhost:8761/eureka/
    healthcheck:
      enabled: true

server:
  port: 9092
