spring:
  config:
    activate:
      on-profile: dev

admin-registry:
  user: dev
  password: dev

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://${admin-registry.user}:${admin-registry.password}@localhost:8761/eureka/
    healthcheck:
      enabled: true

server:
  port: 9092
