spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/wincar_sav_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

admin-registry:
  user: dev
  password: dev
 
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${admin-registry.user}:${admin-registry.password}@localhost:8761/eureka/
    healthcheck:
      enabled: true

server:  
  port: 8089
